//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_no { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public int salary { get; set; }
        public int dept_no { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual emp_project_relation emp_project_relation { get; set; }
        public virtual works_on works_on { get; set; }
    }
}
