//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectView
    {
        public int project_no_emp { get; set; }
        public Nullable<int> project_no_project { get; set; }
    }
}
