//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sampleEntities : DbContext
    {
        public sampleEntities()
            : base("name=sampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<works_on> works_on { get; set; }
        public virtual DbSet<emp_project_relation> emp_project_relation { get; set; }
        public virtual DbSet<ProjectView> ProjectView { get; set; }
    }
    
}
